module OloloMain where

import qualified Tests.Bottles     as Bottles
import qualified Tests.Bridge      as Bridge
import qualified Tests.Hanoi       as Hanoi
import qualified Tests.Reverso     as Reverso
import qualified Tests.Sorto       as Sorto


-- main = do

  ----------------------------------------------------
  ---- FOR PAPER -------------------------------------
  ----------------------------------------------------

--   Reverso.testUnfoldSimplForwardOpt 30
--   Reverso.testUnfoldSimplForwardPes 30
--   Reverso.testUnfoldSimplForwardOpt 60
--   Reverso.testUnfoldSimplForwardPes 60
--   Reverso.testUnfoldSimplForwardOpt 90
--   Reverso.testUnfoldSimplForwardPes 90
--
--   Reverso.testUnfoldSimplFair1_1 10000 30
--   Reverso.testUnfoldSimplFair1_1 10000 60
--   Reverso.testUnfoldSimplFair1_1 10000 90
--   Reverso.testUnfoldSimplFair2_1 11    30
--   Reverso.testUnfoldSimplFair2_1 11    60
--   Reverso.testUnfoldSimplFair2_1 12    90
--
--   Reverso.testUnfoldEssentialArgs1_1 30
--   Reverso.testUnfoldEssentialArgs2_1 30
--   Reverso.testUnfoldEssentialArgs1_1 60
--   Reverso.testUnfoldEssentialArgs2_1 60
--   Reverso.testUnfoldEssentialArgs1_1 90
--   Reverso.testUnfoldEssentialArgs2_1 90
--
--   Reverso.testUnfoldSimpl2_2 30
--   Reverso.testUnfoldSimpl1_2 30
--   Reverso.testUnfoldSimpl2_2 60
--   Reverso.testUnfoldSimpl1_2 60
--   Reverso.testUnfoldSimpl2_2 90
--   Reverso.testUnfoldSimpl1_2 90
--
--   Reverso.testUnfoldSimplFair2_2 10000 30
--   Reverso.testUnfoldSimplFair2_2 10000 60
--   Reverso.testUnfoldSimplFair2_2 10000 90
--   Reverso.testUnfoldSimplFair1_2  7    30
--   Reverso.testUnfoldSimplFair1_2  7    60
--   Reverso.testUnfoldSimplFair1_2  7    90
--
--   Reverso.testUnfoldEssentialArgs2_2 30
--   Reverso.testUnfoldEssentialArgs1_2 30
--   Reverso.testUnfoldEssentialArgs2_2 60
--   Reverso.testUnfoldEssentialArgs1_2 60
--   Reverso.testUnfoldEssentialArgs2_2 90
--   Reverso.testUnfoldEssentialArgs1_2 90
--
--   ----------------------------------------------------
--
--   Sorto.testUnfoldSimpl2 3
--   Sorto.testUnfoldSimpl2 4
--   Sorto.testUnfoldSimpl2 5
--   Sorto.testUnfoldSimpl2 6
--   Sorto.testUnfoldSimpl2 30
--   Sorto.testUnfoldSimpl1 3
--   Sorto.testUnfoldSimpl1 4
--   Sorto.testUnfoldSimpl1 5
--   Sorto.testUnfoldSimpl1 6
--   Sorto.testUnfoldSimpl1 30
--
--   Sorto.testUnfoldSimplFair2 100 3
--   Sorto.testUnfoldSimplFair2 100 4
--   Sorto.testUnfoldSimplFair2 100 5
--   Sorto.testUnfoldSimplFair2 100 6
--   Sorto.testUnfoldSimplFair2 100 30
--   Sorto.testUnfoldSimplFair1 8   3
--   Sorto.testUnfoldSimplFair1 9   4
--   Sorto.testUnfoldSimplFair1 10  5
--   Sorto.testUnfoldSimplFair1 13  6
--   Sorto.testUnfoldSimplFair1 20  30
--
--   Sorto.testUnfoldEssentialArgs2 3
--   Sorto.testUnfoldEssentialArgs2 4
--   Sorto.testUnfoldEssentialArgs2 5
--   Sorto.testUnfoldEssentialArgs2 6
--   Sorto.testUnfoldEssentialArgs2 30
--   Sorto.testUnfoldEssentialArgs1 3
--   Sorto.testUnfoldEssentialArgs1 4
--   Sorto.testUnfoldEssentialArgs1 5
--   Sorto.testUnfoldEssentialArgs1 6
--   Sorto.testUnfoldEssentialArgs1 30
--
--   Sorto.testUnfoldPermSimpl1 3
--   Sorto.testUnfoldPermSimpl1 4
--   Sorto.testUnfoldPermSimpl1 5
--   Sorto.testUnfoldPermSimpl1 6
--   Sorto.testUnfoldPermSimpl2 3
--   Sorto.testUnfoldPermSimpl2 4
--   Sorto.testUnfoldPermSimpl2 5
--   Sorto.testUnfoldPermSimpl2 6
--
--   Sorto.testUnfoldPermSimplFair1 10000 3
--   Sorto.testUnfoldPermSimplFair1 10000 4
--   Sorto.testUnfoldPermSimplFair1 10000 5
--   Sorto.testUnfoldPermSimplFair1 10000 6
--   Sorto.testUnfoldPermSimplFair2 4 3
--   Sorto.testUnfoldPermSimplFair2 5 4
--   Sorto.testUnfoldPermSimplFair2 7 5
--   Sorto.testUnfoldPermSimplFair2 8 6
--
--   Sorto.testUnfoldPermEssentialArgs1 3
--   Sorto.testUnfoldPermEssentialArgs1 4
--   Sorto.testUnfoldPermEssentialArgs1 5
--   Sorto.testUnfoldPermEssentialArgs1 6
--   Sorto.testUnfoldPermEssentialArgs2 3
--   Sorto.testUnfoldPermEssentialArgs2 4
--   Sorto.testUnfoldPermEssentialArgs2 5
--   Sorto.testUnfoldPermEssentialArgs2 6
--   ----------------------------------------------------
--
--   Hanoi.testUnfoldSimpl
--   Hanoi.testUnfoldSimplFair 50
--   Hanoi.testUnfoldEssentialArgs
--
--   Hanoi.testUnfoldSimpl1
--   Hanoi.testUnfoldSimplFair1 5
--   Hanoi.testUnfoldEssentialArgs1
--
-- ----------------------------------------------------
--
--   Bridge.testUnfoldSimpl'
--   Bridge.testUnfoldSimplFair' 20
--   Bridge.testUnfoldEssentialArgs'
--
--   Bridge.testUnfoldSimpl
--   Bridge.testUnfoldSimplFair 19
--   Bridge.testUnfoldEssentialArgs
--
-- ----------------------------------------------------
--   Bottles.testUnfoldSimpl
--   Bottles.testUnfoldSimplBad
--
--   Bottles.testUnfoldSimplFair 10000
--   Bottles.testUnfoldSimplFairBad 5
--
--   Bottles.testUnfoldEssentialArgs
--   Bottles.testUnfoldEssentialArgsBad
